on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: ci

jobs:
    build_documentation:
        name: Documentation
        runs-on: ubuntu-18.04
        env:
            DOXYGEN_VER: 1.8.18
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master

            - name: Install Doxygen
              run: |
                  wget --quiet https://sourceforge.net/projects/doxygen/files/rel-${DOXYGEN_VER}/doxygen-${DOXYGEN_VER}.linux.bin.tar.gz
                  mkdir doxygen
                  tar -xf doxygen-${DOXYGEN_VER}.linux.bin.tar.gz -C doxygen --strip 1

            - name: Configure
              run: |
                  git submodule update --init --recursive
                  mkdir build && cd build
                  cmake -DAF_BUILD_CPU:BOOL=OFF -DAF_BUILD_CUDA:BOOL=OFF \
                        -DAF_BUILD_OPENCL:BOOL=OFF -DAF_BUILD_UNIFIED:BOOL=OFF \
                        -DAF_BUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF \
                        -DBOOST_ROOT:PATH=${BOOST_ROOT_1_72_0} \
                        -DDOXYGEN_EXECUTABLE:FILEPATH=${GITHUB_WORKSPACE}/doxygen/bin/doxygen \
                        ..

            - name: Build
              run: |
                  cd ${GITHUB_WORKSPACE}/build
                  cmake --build . --target docs
